{% set name = "pymde" %}
{% set version = "0.1.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymde-{{ version }}.tar.gz
  sha256: 073b8f7845dfd8dfb523dbd3b26b7f6592e201b1437eead83b7021f7e255dda4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=1.17.5                         # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools >=18.0
    - numpy >=1.17.5
  run:
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pynndescent
    - python
    - scipy
    - pytorch >=1.7.1
    - torchvision >=0.8.2
    - requests
  run_constrained:
    # temporary fix for issue in pytorch feedstock
    # see https://github.com/conda-forge/pytorch-cpu-feedstock/issues/65
    - pytorch-cpu >=1.7.1

test:
  imports:
    - pymde
    - pymde.functions
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs pymde

about:
  home: https://github.com/cvxgrp/pymde
  summary: Minimum-Distortion Embedding
  description: |
    PyMDE is a Python library for computing vector embeddings for finite sets of
    items, such as images, biological cells, nodes in a network, or any other
    abstract object.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
    - akshayka
