{% set name = "pymde" %}
{% set version = "0.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymde-{{ version }}.tar.gz
  sha256: 24aca4f8bd0b3276de8311e3a8d15b5da99dc7eb6eae8690f0c1c999a3e2ee5b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools >=18.0
    - numpy >=1.17.5
  run:
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pynndescent
    - python
    - scipy
    - pytorch >=1.7.1
    - torchvision >=0.8.2
    - requests

test:
  imports:
    - pymde
    - pymde.functions
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs pymde

about:
  home: https://github.com/cvxgrp/pymde
  summary: Minimum-Distortion Embedding
  description: |
    PyMDE is a Python library for computing vector embeddings for finite sets of
    items, such as images, biological cells, nodes in a network, or any other
    abstract object.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
    - akshayka
